<?php
/**
 * Created by PhpStorm.
 * User: HeYiwei
 * Date: 2018/6/2
 * Time: 14:37
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\model\ServerProject;
use app\common\model\Technician;

class Api extends AdminBase
{
    protected $serve_project_model;
    protected $technician_model;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->serve_project_model  = new ServerProject();
        $this->technician_model     = new Technician();
    }

    /**
     * 获取服务项目
     */
    public function getServerList(){
        if( $this->request->isPost()){
            $params = $this->request->param();
            if( $params['key'] == 'server' ){ //查找服务项目
                $row = $this->serve_project_model->getList($params);
            }elseif($params['key'] == 'technician'){//查找技师
                $row = $this->technician_model->getList($params);
            }
            return json(['data'=>$row,'code'=>1,'message'=>'操作完成']);
        }
    }

    public function getServerInfo(){
        if( $this->request->isPost()){
            $params = $this->request->param();
            if( $params['key'] == 'server' ){ //查找服务项目
                $row = $this->serve_project_model->getInfo($params);
            }elseif($params['key'] == 'technician'){//查找技师
                $row = $this->technician_model->getInfo($params);
            }
            return json(['data'=>$row,'code'=>1,'message'=>'操作完成']);
        }
    }
}