<?php
/**
 * Created by PhpStorm.
 * User: HeYiwei
 * Date: 2018/5/30
 * Time: 13:35
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\model\Book as BookModel;
use think\Db;

class Book extends AdminBase
{
    protected $book_model;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->book_model = new BookModel();
    }

//    订单列表
    public function order()
    {
        $list = $this->book_model->alias('b')->join('user u','b.u_id=u.id')->where([
            'b.s_id' => $this->admin_id
        ])->field('b.id,b.type,b.project_id,b.price,b.status,b.time,b.remark,u.username,u.mobile,u.uni_id,u.portrait')->order('b.id desc')->select();
        foreach ($list as $k => &$v) {
            $statusNote = config('book.status');
            $v['status_note'] = $statusNote[$v['status']];
            if ($v['type'] == 1) {
                $v['type'] = '技师预约';
                $project = Db::name('technician')->where([
                    'id' => $v['project_id']
                ])->field('id,name,mobile,cover_pic,status')->find();
            }
            if ($v['type'] == 2) {
                $v['type'] = '服务预约';
                $project = Db::name('server_project')->where([
                    'id' => $v['project_id']
                ])->field('id,name,status,cover_pic')->find();
            }
            $v['project'] = $project;
        }
        return $this->fetch('',['list'=>$list]);
    }

    /**
     * 修改订单
     * */

    public function update(){
        if( $this->request->isPost()){
            $params = $this->request->param();
            $data = [];
            if($params['field'] == 'status'){
                $data = [
                    'status' =>$params['param']
                ];
            }
            $row = $this->book_model->where([
                'id' =>$params['id']
            ])->update($data);

            if( $row){
                $this->success('修改成功');
            }else{
                $this->error('网络异常');
            }
        }
    }
    public function orderDelete($id = 0, $ids = [])
    {
        $id = $ids ? $ids : $id;
        if ($id) {
            if ($this->book_model->destroy($id)) {
                $this->success('删除成功');
            } else {
                $this->error('删除失败');
            }
        } else {
            $this->error('请选择需要删除的订单');
        }
    }

}