<?php
/**
 * Created by PhpStorm.
 * User: HeYiwei
 * Date: 2018/6/27
 * Time: 11:27
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;

class Cashier extends AdminBase
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        return $this->fetch();
    }
}