<?php
/**
 * Created by PhpStorm.
 * User: HeYiwei
 * Date: 2018/6/9
 * Time: 16:00
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\model\Notice as NoticeModel;
class Notice extends AdminBase
{
    protected  $notice_model;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->notice_model = new NoticeModel();
    }

    public function index(){
        $notice = $this->notice_model->where(['s_id'=>$this->admin_id])->select();

        return $this->fetch('',['notice'=>$notice]);
    }

    /**
     * 添加公告
     */
    public function addNotice(){
        $notice = $this->request->param('notice');
        $row = $this->notice_model->insertGetId([
            's_id' => $this->admin_id,
            'notice' => $notice,
            'status' => 1,
            'add_time' => date('Y-m-d H:i:s',time())
        ]);
        if($row){
            $this->success('添加成功','',$row);
        }else{
            $this->error('网络异常');
        }
    }

    /**
     * 修改状态
     */
    public function updateNotice( $id,$status ){
        $status = $status == 1 ?0:1;
        $row = $this->notice_model->where([
            'id'=>$id,
            's_id'=>$this->admin_id
        ])->update([
            'status'=>$status
        ]);
        if($row){
            $this->success('添加成功','',$row);
        }else{
            $this->error('网络异常');
        }
    }
    /**
     * 删除公告
     */
    public function delNotice( $id ){
        $row = $this->notice_model->where([
            'id'=>$id,
            's_id'=>$this->admin_id
        ])->delete();
        if($row){
            $this->success('修改成功','',$row);
        }else{
            $this->error('网络异常');
        }
    }


}