<?php
/**
 * 提成模板
 * User: HeYiwei
 * Date: 2018/6/24
 * Time: 15:25
 */

namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\model\RoyaltiesTemplate;

class Royalties extends AdminBase
{
    protected $royalties;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->royalties = new RoyaltiesTemplate();
    }


    /**
     * 模板列表
     * @return mixed
     */
    public function index(){
        $royalties = $this->royalties->where([
            's_id' => $this->admin_id
        ])->select();

        return $this->fetch('',['royalties'=>$royalties]);
    }

    /**
     * 添加模板
     * @return mixed
     */
    public function add(){
        return $this->fetch();
    }

    /**
     * 保存模板
     */
    public function save(){
        if( $this->request->isPost() ){
            $data = $this->request->param();
            $validate = $this->validate($data,'Royalties');
            $data['s_id'] = $this->admin_id;
            if( $validate ){
                if( $this->royalties->allowField(true)->save($data)){
                    $this->success('添加成功');
                }else{
                    $this->error('添加失败');
                }
            }else{
                $this->error($validate);
            }

        }
    }

    /**
     * 编辑
     * @param $id
     * @return mixed
     */
    public function edit( $id ){
        $info = $this->royalties->where([
            's_id' => $this->admin_id,
            'id'   => $id
        ])->find();

        return $this->fetch('',['info'=>$info]);

    }

    /**
     * 修改
     */
    public function update(){
        if( $this->request->isPost()){
            $data = $this->request->param();
            $validate = $this->validate($data,'Royalties');
            $data['s_id'] = $this->admin_id;
            if( $validate ){

                if($this->royalties->allowField(true)->save($data, ['id'=>$data['id'],'s_id'=>$this->admin_id]) !== false){
                    $this->success('修改成功');
                }else{
                    $this->error('修改失败');
                }
            }else{

                $this->error($validate);
            }
        }
    }
}