<?php
/**
 * Created by PhpStorm.
 * User: HeYiwei
 * Date: 2018/6/11
 * Time: 13:22
 */

namespace app\admin\controller;


use app\common\model\UserDeal;
use app\common\controller\AdminBase;
use think\Db;

class Sell extends AdminBase
{
    protected $deal_model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->deal_model = new UserDeal();
    }

    /**
     * 消费流水统计
     * @return mixed
     */
    public function turnover(){
        $start_time = $this->request->param('start_time',date('Y-m-d'));
        $end_time = $this->request->param('end_time',date('Y-m-d'));
        $start = $start_time.' 00:00:00';
        $end = $end_time.' 24:59:59';
        $list = $this->deal_model->alias('d')->join('user u','u.id=d.u_id','LEFT')
            ->where(['d.time'=>['>',$start]])
            ->where(['d.time' => ['<',$end]])
            ->field('d.*,u.username,u.uni_id,u.mobile')->where([
            'd.s_id' => $this->admin_id
        ])->order('d.id desc')->select();

        $money = $this->deal_model->where(['time'=>['>',$start]])
            ->where('s_id',$this->admin_id)
            ->where(['time' => ['<',$end]])->sum('money');

        return $this->fetch('',['controller'=>'turnover','list'=>$list,'money'=>$money,'start_time'=>$start_time,'end_time'=>$end_time]);
    }

    /**
     * 统计报表
     */
    public function statistics(){
        if( $this->request->isPost()){
            //每日统计数据列表
            $daySql = 'SELECT  SUM(money) AS money,  DATE_FORMAT(time,\'%m-%d\') AS dateTime  FROM  os_user_deal  WHERE s_id='.$this->admin_id.' GROUP BY DATE_FORMAT(time,\'%m-%d\') ';
            $dayList = Db::name('user_deal')->query($daySql);
            $monthSql = 'SELECT  SUM(money) AS money,  MONTH(time) AS dateTime  FROM  os_user_deal  WHERE s_id='.$this->admin_id.' GROUP BY MONTH(time) ';
            $monthList = Db::name('user_deal')->query($monthSql);
            $yearsSql = 'SELECT  SUM(money) AS money,  YEAR(time) AS dateTime  FROM  os_user_deal WHERE s_id='.$this->admin_id.' GROUP BY YEAR(time) ';
            $yearsList = Db::name('user_deal')->query($yearsSql);

            //用户消费排行榜
            $userRanking =  Db::name('user_deal')->alias('d')->join('user u','u.id=d.u_id','LEFT') ->field('SUM(d.money) as money,COUNT(d.id) as number,u.username,u.uni_id,u.mobile')->where([
                'd.s_id'        => $this->admin_id,
                'deal_type'   => 3
            ])->group('d.u_id')->order('money desc')->select();

            //余额统计[按会员分组]
            $balance = Db::name('user')->alias('u')->join('user_rank r','u.rank_id = r.id','LEFT')->where([
                'u.s_id'        => $this->admin_id
            ])->field('SUM(u.balance) as balance, SUM(u.give_balance) as give_balance,r.name')->group('u.rank_id')->select();
            $countBalance = 0;
            foreach ($balance as $v){
                $countBalance += ($v['balance']*100);
                $countBalance += ($v['give_balance']*100);
            }

            $this->success('查询成功','',['data'=>[
                'dayList' => $dayList,
                'monthList' => $monthList,
                'yearsList' => $yearsList,
                'userRanking' => $userRanking,
                'countBalance' => $countBalance/100,
                'balance' => $balance
            ]]);
        }else{
            return $this->fetch('');
        }
    }
}