<?php
/**
 * Created by PhpStorm.
 * User: HeYiwei
 * Date: 2018/5/30
 * Time: 14:41
 */

namespace app\admin\controller;

use app\common\controller\AdminBase;
use app\common\model\UserRank as UserRankModel;
class UserRank extends AdminBase
{
    protected  $rank_model;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->rank_model = new UserRankModel();
    }

    /**
     * 用户级别
     * @return mixed
     */
    public function index()
    {
        $rank_list = $this->rank_model->where(['status'=>1,'s_id'=>$this->admin_id])->select();

        if( $this->request->isPost()){
            return $this->success('获取成功','',$rank_list);
        }else {
            return $this->fetch('index', ['rank_list' => $rank_list]);
        }

    }

    /**
     * 添加用户级别
     * @return mixed
     */
    public function add()
    {
        return $this->fetch();
    }

    /**
     * 保存用户级别
     */
    public function save()
    {
        if ($this->request->isPost()) {
            $data            = $this->request->param();
            $data['s_id']   = $this->admin_id;
            if ($this->rank_model->allowField(true)->save($data)) {
                $this->success('保存成功');
            } else {
                $this->error('保存失败');
            }
        }
    }

    /**
     * 编辑用户级别
     * @param $id
     * @return mixed
     */
    public function edit($id)
    {
        $rank = $this->rank_model->where(['id'=>$id,'s_id'=>$this->admin_id])->find();
        return $this->fetch('edit', ['rank' => $rank]);
    }

    /**
     * 更新用户级别
     * @param $id
     */
    public function update($id)
    {
        if ($this->request->isPost()) {
            $data            = $this->request->param();

            if ($this->rank_model->allowField(true)->save($data, ['id'=>$id,'s_id'=>$this->admin_id]) !== false) {
                $this->success('更新成功');
            } else {
                $this->error('更新失败');
            }
        }
    }

    /**
     * 删除用户级别
     * @param $id
     */
    public function delete($id)
    {
        if ($this->rank_model->destroy([
            'id'=>$id,'s_id'=>$this->admin_id
        ])) {
            $this->success('删除成功');
        } else {
            $this->error('删除失败');
        }
    }
}