<?php
/**
 * Created by PhpStorm.
 * User: HeYiwei
 * Date: 2018/6/2
 * Time: 17:02
 */

namespace app\common\model;


use think\Db;
use think\Model;

class UserDeal extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function deal($params,$s_id){

        //修改用户账户数据
        $user = Db::name('user')->where([
            'id' => $params['u_id']
        ]);
        if($params['type'] == 1){
            $userRow = $user->setInc('balance',$params['money']);
        }else{
            $userRow = $user->setDec('balance',$params['money']);
        }

        //添加交易记录
        if($userRow){
           $dealRow = Db::name('user_deal')->insert([
                'u_id' =>$params['u_id'],
                'type' =>$params['type'],
                'money' =>$params['money'],
                'remark' => $params['remark'],
                'time'   => date('Y-m--d H:i:s',time()),
                's_id'  => $s_id,
               'deal_type' => 3
            ]);
        }

        return $dealRow;
    }
}